spring:
  datasource:
    url: "jdbc:postgresql://localhost:54322/postdb"
    username: "master"
    password: "postdb_password"

  jpa:
    hibernate:
      ddl-auto: update

service:
  user:
    url: "http://localhost:8090"
