apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config-map
  namespace: k8s-program
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://userdb:5432/postgres"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: post-config-map
  namespace: k8s-program
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postdb:5432/postgres"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: userdb-init-scripts
  namespace: k8s-program
data:
  create-tables.sql: |
    create table if not exists public.user_details
    (
        id bigserial primary key,
        amount_of_posts bigint,
        username varchar(255) constraint ukqqadnciq8gixe1qmxd0rj9cyk unique
    );

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postdb-init-scripts
  namespace: k8s-program
data:
  create-tables.sql: |
    create table if not exists public.post_details
    (
        id bigserial primary key,
        author_id bigint,
        posted_at date,
        text varchar(255)
    );




