apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: k8s-program
  labels:
    deployment: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: turkogluc/user-service:1.0.0
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://userdb:5432/postgres"
          - name: SPRING_DATASOURCE_USERNAME
            value: "master"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "userdb_password"

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: user-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  namespace: k8s-program
  labels:
    deployment: post
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
      - name: post-api
        image: turkogluc/post-service:1.0.0
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postdb:5432/postgres"
          - name: SPRING_DATASOURCE_USERNAME
            value: "master"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "postdb_password"
          - name: SERVICE_USER_URL
            value: "http://user-service:8080"

---

apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: post-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30095
