apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: k8s-program
  labels:
    deployment: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: turkogluc/user-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: user-config-map
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: user-db-credentials
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-db-credentials
                key: password

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: user-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  namespace: k8s-program
  labels:
    deployment: post
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
      - name: post-api
        image: turkogluc/post-service:1.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: post-config-map
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: post-db-credentials
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: post-db-credentials
                key: password
          - name: SERVICE_USER_URL
            value: "http://user-service:8080"

# Rollback commands
#kubectl rollout history deployment post-deployment
#kubectl rollout undo deployment post-deployment --to-revision=1
#kubectl rollout status deployment post-deployment
---

apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: post-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30095
