spring:
  datasource:
    url: "jdbc:postgresql://localhost:54321/userdb"
    username: "master"
    password: "userdb_password"

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: "org.hibernate.dialect.PostgreSQLDialect"

management:
  endpoint:
    health:
      probes:
        enabled: true
