apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config-map
  namespace: {{ .Values.namespace }}
data:
  SPRING_DATASOURCE_URL: "{{ .Values.db.user.url }}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: post-config-map
  namespace: {{ .Values.namespace }}
data:
  SPRING_DATASOURCE_URL: "{{ .Values.db.post.url }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: userdb-init-scripts
  namespace: {{ .Values.namespace }}
data:
  create-tables.sql: |
    create table if not exists public.user_details
    (
        id bigserial primary key,
        amount_of_posts bigint,
        username varchar(255) constraint ukqqadnciq8gixe1qmxd0rj9cyk unique
    );

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postdb-init-scripts
  namespace: {{ .Values.namespace }}
data:
  create-tables.sql: |
    create table if not exists public.post_details
    (
        id bigserial primary key,
        author_id bigint,
        posted_at date,
        text varchar(255)
    );
