# Default values for posting-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

db:
  user:
    image: "postgres:latest"
    database: "userdb"
    url: "jdbc:postgresql://userdb:5432/userdb"

  post:
    image: "postgres:latest"
    database: "postdb"
    url: "jdbc:postgresql://postdb:5432/postdb"

app:
  user:
    replica: 2
    image: "turkogluc/user-service:1.3.0"
    serviceType: "ClusterIP"

  post:
    replica: 2
    image: "turkogluc/post-service:1.3.0"
    serviceType: "ClusterIP"
    userServiceUrl: "http://user-service:8080"

namespace: "k8s-program"
